### ISSUE TITLE
rainTotal is not pulling correct data

### ISSUE THREAD

**Issue by techfixpros** [RandomReaper/weewx-zabbix#2]
RainTotal is currently showing 55 every day, even without raining. It rained 0.4" the other day and the value did not increase.

Feb 15 09:44:55 john-PS583AA-ABA-a1020n weewx[4213]: zabbix: sandvine.lan weewx_rain_total 55.245

Weewx 3.9.1

The rest of the values seem to be correct and are updating properly from the correct sources.

**Comment by RandomReaper** [comment]
Can you please enable debug log and post it?

If I remember correctly, it can be set in `weewx.conf`:


     debug = 1

**Comment by techfixpros** [comment]
Do you need a loop/archive cycle or just the startup?

**Comment by RandomReaper** [comment]
In fact the only line I wanted to see is the line you already provided...
`Feb 15 09:44:55 john-PS583AA-ABA-a1020n weewx[4213]: zabbix: sandvine.lan weewx_rain_total 55.245`

The code of `weewx-zabbix` only iterate through the values provided by weewx, and push them to zabbix. I think this incorrect value is also stored by weewx, so this plugin can't do anything about it.
